### PR TITLE
feat:(FSADT1-664): adding native support

### PR DESCRIPTION
**Pull request by paulushcgcj**
# Description

Adding support to native image builds

Fixes FSADT1-664

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[API](https://nr-forest-client-api-123-backend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-forest-client-api/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by mamartinezmejia — APPROVED** [review]

**Review by mishraomp — APPROVED** [review]
native images with oracle DB, 👍🏼 🥇 

nicely done, kudos.

**Review by DerekRoberts — APPROVED** [review]
Cloud native!  I must steal this, preferably in an Action.  :D

**Comment by paulushcgcj** [comment]
Just a few caveats from this change to let both @mishraomp and @DerekRoberts aware of.

1. Native images got a few issues with reflection, so keep in mind some reflection-based code can backfire. You can generate some files to help the native image find out about your reflection code but it can fail your build depending on what you're using.
2. Webflux Functional doesn't work properly with native images, keep up with annotation-based endpoints for now (depending on what you're doing, you can do the trick I mentioned above, but I don't recommend it for now)
3. Oracle certificates were a pain, but it's an easy fix, you can pass the certificate path through a query string and you can use an init container to extract the certificate for you
4. Swagger works fine but only with annotation-based endpoints. For some reason, it failed while testing the endpoint through swagger, but when testing using postman worked just fine
5. It takes a lot of time to build, but it is worth it. It's better to set a few parameters in the pom to set some of the buildpacks, labels and version
6 - For now, it's not possible to turn this build part into action as it requires some environment variable settings. Maybe we can try in the future to pass it as environment variables and see how it goes
7 - It looks like it's not using the distress build, but the ubuntu one, we can try to rework this in the future if it becomes a problem

**Comment by mishraomp** [comment]
whats the startup time for the actual container (not including the init one) and the CPU and memory stats? @paulushcgcj

**Comment by paulushcgcj** [comment]
> whats the startup time for the actual container (not including the init one) and the CPU and memory stats? @paulushcgcj

The startup time is between 0.7 and 1.9 seconds. I think we will not be able to reduce it even more due to database checks that the oracle client does when booting up. Other factors such as flyway can also delay the startup time, but we can expect (even with flyway) less than 2 seconds of startup time.

In terms of resource usage
image

**Comment by mishraomp** [comment]
@paulushcgcj thanks for the stats, the startup time is great,  I think the spring boot team needs to do some work around the memory, 128 is high for a native one.

**Comment by paulushcgcj** [comment]
> @paulushcgcj thanks for the stats, the startup time is great, I think the spring boot team needs to do some work around the memory, 128 is high for a native one.

True. It could be due to connection pools and webflux thread pools as well, but for now, it is something to be discussed with them.

**Pull request merged**
