### PR TITLE
feat(FSADT1-1307): adding search by ids

### LINKED ISSUE #217: List forest clients by list of ids
As a forest client api user I want to be able to submit a list of forest client ids So that the endpoint returns me a list of matching forest clients

**Additional Context**
- Endpoint needs to accept a list of ids as a parameter
- Endpoint should return a list of forest clients

**Acceptance Criteria**
- [x] Given one ID, When searching for forest clients, Then return a list of forest clients
- [x] Given many IDs, When searching for forest clients, Then return a list of forest clients

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

### PR DESCRIPTION
**Pull request by paulushcgcj**
# Description

As a forest client api user I want to be able to submit a list of forest client ids So that the endpoint returns me a list of matching forest clients.

Fixes #217

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] New integrated tests

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[API](https://nr-forest-client-api-218-backend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-forest-client-api/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by mamartinezmejia — APPROVED** [review]

**Comment by craigyu** [comment]
Works great! does it have to be paginated though?

**Review by craigyu — APPROVED** [review]

**Comment by craigyu** [comment]
I was expecting it to be under its own endpoint, similar to `/api/clients/findByClientNumber/{clientNumber}`, like `/api/clients/findByClientNumbers`

**Comment by paulushcgcj** [comment]
> Works great! does it have to be paginated though?

Yes, as it prevents an overflow of data. Keep in mind that nothing prevents you from requesting 100 items per page though

**Comment by paulushcgcj** [comment]
> I was expecting it to be under its own endpoint, similar to `/api/clients/findByClientNumber/{clientNumber}`, like `/api/clients/findByClientNumbers`

We're reworking some of the endpoints naming convention. This one is a more straightforward endpoint, as it is related to search. The idea is all future global search (something that does not have a specific filter like search actives or search individuals only) will be handled here, and you will be able to group multiple query parameters at once to compound your search.

For now you can use multiple IDs, but in the future you can want to search some IDs and want to limit it to be for one specific type and so on.

**Comment by craigyu** [comment]
> > Works great! does it have to be paginated though?
> 
> Yes, as it prevents an overflow of data. Keep in mind that nothing prevents you from requesting 100 items per page though

My preference is to have this feature under its own endpoint, you could put an upper limit, say 50, but this works too :D

**Pull request merged**
